1st task from module-0
js-tasks-ru/jsbasic-20201022_dmitriy10 pull request #1
Opened 2020-10-25 16:08 UTC by dbalukovastraone

Added function sum in index.js

2020-10-26 15:14 UTC, dbalukovastraone commented
@koalex , затупил и не добавил Вас в Asignees.

2020-10-26 15:18 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 0-module/1-task/task.test.js — изменен
```

2020-10-26 15:36 UTC, dbalukovastraone commented
загрузил из репозитория таск снова, изменения внес только в index.js.

2020-10-26 16:08 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 0-module/1-task/task.test.js — изменен
```

2020-10-26 17:15 UTC, jsru commented
Пожалуйста, не меняйте «системные» файлы.
          Задача не может считаться решенной, если были изменены файлы тестов или другие «системные» файлы.
          Следующие файлы были изменены:
```diff
- 0-module/1-task/task.test.js — изменен
```

2020-10-27 14:20 UTC, koalex requested changes
Откати коммит, который поменял package.json. Если не знаешь как, то напиши мне - созвонимся и я покажу

2020-10-27 14:20 UTC, koalex commented on package.json
> -    "karma": "^4.0.0",
вот это нужно откатить обратно иначе тесты не пройдут

2020-10-29 15:47 UTC, dbalukovastraone commented on package.json
> -    "karma": "^4.0.0",
да, хорошо, спасибо. Сегодня откачу обратно.

2020-11-16 05:16 UTC, closed without merging